version: 2.1
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context:
            - npm
            - github
jobs:
  build:
    docker:
      - image: cimg/node:16.0.0
    working_directory: ~/project
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run: npm ci
      - run: npm run build
      - run: npm test
      - when:
          condition:
            equal:
              - main
              - <<pipeline.git.branch>>
          steps:
            - run: npm run semantic-release
